image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .
  - pip install pytest-cov pytest-mock coveralls
  - pip install keyrings.alt

test:
  script:
    - py.test tests
    - py.test --cov-report=term --cov-config=.coveragerc --cov=messages tests/unit --cov=flask_discord
